import {
  FiHome,
  FiInfo,
  FiGrid,
  FiUsers,
  FiMail,
  FiSearch,
  FiMenu,
  FiX,
  FiChevronDown,
  FiChevronUp,
} from 'react-icons/fi';

export const NAV_ITEMS = [
  {
    label: 'HOME',
    href: '/',
    icon: FiHome,
    iconClass: 'text-current',
  },
  {
    label: 'ABOUT US',
    href: '/about-us',
    icon: FiInfo,
    iconClass: 'text-current',
  },
  {
    label: 'MODULES',
    href: '/modules',
    icon: FiMail,
    iconClass: 'text-current',
    dropdown: {
      items: [
        { label: 'Academics', href: '/modules/academics' },
        { label: 'Alumni', href: '/modules/alumni' },
        { label: 'Attendance', href: '/modules/attendance' },
        { label: 'Behaviour', href: '/modules/behaviour' },
        { label: 'Certificates', href: '/modules/certificates' },
        { label: 'Communication', href: '/modules/communication' },
        { label: 'Downloads', href: '/modules/download' },
        { label: 'Exams', href: '/modules/exams' },
        { label: 'Finance', href: '/modules/finance' },
        { label: 'CMS', href: '/modules/cms' },
        { label: 'FrontOffice', href: '/modules/frontoffice' },
        { label: 'Homework', href: '/modules/homework' },
        { label: 'Hostel', href: '/modules/hostel' },
        { label: 'HR', href: '/modules/hr' },
        { label: 'Inventory', href: '/modules/inventory' },
        { label: 'Lessons', href: '/modules/lessons' },
        { label: 'Library', href: '/modules/library' },
        { label: 'Branches', href: '/modules/branches' },
        { label: 'Assessment', href: '/modules/assessment' },
        { label: 'Reports', href: '/modules/reports' },
        { label: 'Students', href: '/modules/students' },
        { label: 'Syllabus', href: '/modules/syllabus' },
        { label: 'Transport', href: '/modules/transport' },
      ],
    },
  },
  {
    label: 'INTEGRATIONS',
    href: '/integrations',
    icon: FiGrid,
    iconClass: 'text-current',
  },
  {
    label: 'CAREERS',
    href: '/',
    icon: FiUsers,
    iconClass: 'text-current',
  },
  {
    label: 'CSR',
    href: '/csr',
    icon: FiMail,
    iconClass: 'text-current',
  },
  {
    label: 'AFFILIATE',
    href: '/affiliate',
    icon: FiMail,
    iconClass: 'text-current',
  },
  {
    label: 'DIARY',
    href: '/diary',
    icon: FiMail,
    iconClass: 'text-current',
  },
  {
    label: 'CONTACT',
    href: '/contact-us',
    icon: FiMail,
    iconClass: 'text-current',
  },
];

export const ICONS = {
  search: FiSearch,
  bars: FiMenu,
  times: FiX,
  chevronDown: FiChevronDown,
  chevronUp: FiChevronUp,
};
